inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'

# Rails
Rails:
  Enabled: true

# RSpec
RSpec:
  Enabled: true